### ISSUE TITLE
티어가 안보여요 

### ISSUE THREAD

**Issue by hanchaoa** [mrz1277/LoLStats#1]
이 앱도 너무 잘쓰고잇습니다 매우 좋네요, 다름이아니라 티어가 안보입니다 지금 롤을꺼서 스크린샷을 찍을순없는데 사용룬, 평점,승률은 보이는데 티어가 안보이네요, 바탕화면은 하얀색인데 그거땜에 안보이는건지 모르겟네요ㅎㅎ.. 이 앱도 정말 편합니다 감사합니다

**Comment by mrz1277** [comment]
정말 그렇네요. 확인해보니 얼마전에 라이엇측에서 티어랑 streak(연승) 보여주던 API를 변경했네요. 관련 사항 수정해서 앱스토어에 업데이트 요청했으니 승인되면 아마 몇 일 내로 업데이트 되실겁니다. 리폿해주셔서 감사합니다.^^

**Comment by mrz1277** [comment]
@hanchaoa 앱 심사전에 미리 사용해보실 수 있게 링크 하나 첨부합니다 https://github.com/mrz1277/LoLStats/releases/download/v1.3/LoL.Stats.zip
